# .github/workflows/lint.yml
name: Lint Codebase

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

jobs:
  super-linter:
    name: Run Super Linter on All Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GitHub Super-Linter
        uses: github/super-linter@v6
        env:
          # GitHub token for reporting results
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Lint entire codebase
          VALIDATE_ALL_CODEBASE: true

          # Optional general settings
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .
