name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-title:
    if: github.event.pull_request.state != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: PR Title Validation
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
          requireScope: false
